### ISSUE TITLE
Remove load listener

### ISSUE THREAD

**Issue by maanlamp** [jeroentvb/web-app-from-scratch-18-19#4]
https://github.com/jeroentvb/web-app-from-scratch-18-19/blob/49d8394dfbf904bd3ce5e842346967f6ce5db810/week1/public/js/app.js#L16

You are loading this script at the bottom of your HTML, the entire body is already loaded at that point, so you don't have to set this.

**Comment by joostf** [comment]
Furthermore you can load module scripts from the head section, because they are deferred by default.
